version: "3.9"

services:
  api:
    build:
      context: ./api/Master_Schedule
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      PORT: "8080"
    restart: unless-stopped

  ui:
    build:
      context: ./ui/macaw
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      PORT: "3000"
      VITE_API_DOMAIN: "http://api:8080" 
    restart: unless-stopped

networks:
  default:
    name: macaw_net